x-common: &common
  ulimits:
    nofile: { soft: 1048576, hard: 1048576 }
  restart: always

x-logging: &logging
  logging:
    driver: json-file
    options: { max-size: 100m, max-file: 5 }

services:
  caddy:
    image: caddy:2.11.2
    container_name: caddy-remnawave
    hostname: caddy-remnawave
    <<: [*common, *logging]
    network_mode: host
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - /var/www/html:/var/www/html:ro
      - /dev/shm:/dev/shm:rw
      - caddy_data:/data
    command: sh -c 'rm -f /dev/shm/nginx.sock && caddy run --config /etc/caddy/Caddyfile --adapter caddyfile'
    environment:
      - CADDY_SOCKET_PATH=/dev/shm/nginx.sock
      - SELF_STEAL_DOMAIN=#DOMAIN#

  remnanode:
    image: remnawave/node:latest
    container_name: remnanode
    hostname: remnanode
    <<: [*common, *logging]
    network_mode: host
    cap_add: [ NET_ADMIN ]
    environment:
      - NODE_PORT=2222
      - SECRET_KEY=#SECRET_KEY#
    volumes:
      - /dev/shm:/dev/shm:rw

volumes:
  caddy_data:
